solution/course/config/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import LoginView, log_out

from notes.views import redirect_to_note_detail
# from common.views import HomeView

from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="common/home.html"), name="home"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('admin/', admin.site.urls),
    path('<int:note_id>/', redirect_to_note_detail),
    path('notes/', include("notes.urls", namespace="notes")),
    path('todo/', include("todo.urls", namespace="todo")),
]

solution/course/todo/urls.py
"""ToDo URL Configuration."""
from django.urls import path

from todo.views import TodoDetails

app_name = "todo"
urlpatterns = [
    path('<int:todo_id>/', TodoDetails.as_view(), name="details"),
]

solution/course/common/models.py
"""Data for the common views"""
from config.store import CustomStore
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import make_password
from django.contrib.postgres.fields import ArrayField
from django.conf import settings


class UserStore(CustomStore):
    """Store for the users."""

    model_name = "users"
    backup = [
        {
            "name": "admin",
            "password": make_password("admin"),
            "role": "admin"
        },
        {
            "name": "james",
            "password": make_password("hendrix"),
            "role": "editor"
        },
        {
            "name": "fred",
            "password": make_password("baggins"),
            "role": "user"
        },
        {
            "name": "ganesh",
            "password": make_password("the_grey"),
            "role": "user"
        }
    ]


class CustomUser(AbstractUser):
    
    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('editor', 'Editor'),
        ('user', 'User'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')
    voted_notes = ArrayField(models.CharField(), default=list, blank=True)


class Notes(models.Model):
    
    SECTION_CHOICES = [
        ('Web Frameworks', 'Web Frameworks'),
        ('Setting up Django','Setting up Django'),
        ('URL Mapping','URL Mapping'),
    ]

    text = models.TextField()
    section = models.CharField(max_length=50, choices=SECTION_CHOICES)
    

class Votes(models.Model):
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    note = models.ForeignKey(Notes, on_delete=models.CASCADE, related_name='user_votes')
    votes = models.BooleanField(default=False)
    section = models.CharField(max_length=50, blank= True)
    
    class Meta:
        unique_together = ('user', 'note')

solution/course/common/forms.py
"""Common forms to various apps."""

from django import forms


class LoginForm(forms.Form):
    """A simple login form."""

    user_name = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

solution/course/common/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render, redirect
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView
from django.urls import reverse, reverse_lazy
# Create your views here.


class LoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'common/login.html'
    redirect_authenticated_user =True

    def get_success_url(self) -> str:
        return reverse_lazy('home')
    
    def form_valid(self, form):
        
        
        response = super().form_valid(form)
        
        user_role = self.request.user.role
        
        if user_role in ['admin', 'editor']:
            self.request.session['can_write_notes'] = True
        else:
            self.request.session['can_write_notes'] = False
        
        return response
    
    def dispatch(self, request: HttpRequest, *args: reverse_lazy, **kwargs: reverse_lazy) -> HttpResponse:
        if self.redirect_authenticated_user and request.user.is_authenticated:
            return redirect(self.get_success_url())
        return super().dispatch(request, *args, **kwargs)

def log_out(request):
    logout(request)
    return redirect('home')

solution/course/common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My website</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <header>
      <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'notes:home' %}">My Course Notes</a></li>
        <li><a href="{% url 'todo:details' todo_id=1 %}">My ToDo List</a>
        {% if user.is_authenticated %}
        <li> Logged in as {{ user.username }} <a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Log in</a></li>
        {% endif %} 
      </ul>
    </header>
    <section>
      {% block content %}
      {% endblock %}
    </section>
    <footer>
      &copy; to me! I am not using any cookies ... yet!
    </footer>
  </body>
</html>

solution/course/common/templates/common/home.html
{% extends 'common/base.html' %}

{% block content %}
<h1>Welcome to my new website!</h1>
<p>Feel free to browse through my notes or check my To Do list using the menu on the top.</p>
{% endblock %}

solution/course/common/templates/common/login.html
{% extends 'common/base.html' %}

{% block content %}
<form method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <div>
        <input type='submit' value='Submit'/>
    </div>
</form>
{% endblock %}